### ISSUE TITLE
nginx commit ab9038a broke the dynamic_tls_records patch

### ISSUE THREAD

**Issue by i81b4u** [nginx-modules/ngx_http_tls_dyn_size#1]
nginx commit ab9038a -> SSL: support for TLSv1.3 early data with OpenSSL broke the dynamic_tls_records patch (nginx__dynamic_tls_records_1.13.0+.patch) due to changes in ngx_event_openssl.h.

I attached an updated patch that can be applied to nginx as of commit ab9038a: [nginx__dynamic_tls_records_1.15.3+.zip](https://github.com/nginx-modules/ngx_http_tls_dyn_size/files/2407822/nginx__dynamic_tls_records_1.15.3%2B.zip)

**Comment by denji** [comment]
https://github.com/nginx-modules/ngx_http_tls_dyn_size/commit/5e3b560d49c0b830e7aea5bc996e244e3f297618
